### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by himanshush13** [trr-official/abapunit2junit#13]
![image](https://user-images.githubusercontent.com/36809136/81793122-89b72b00-9526-11ea-8248-303926025532.png)

I am getting this error, while using the scripts. 
Please if anyone can give their insight.

**Comment by matt1as** [comment]
The error means it cannot find the server,please make sure you have the correct name and that the script is allowed to access the server and that is not behind a firewall or proxy.

**Comment by himanshush13** [comment]
The host name is correct, but I think its in a private network, that is the issue. 
If I try to open the ports, and as Azure is on open network (source ip - internet) will it solve my problem ?

**Comment by matt1as** [comment]
It should work

We did setup a build server on our private network that runs this script (and others) that is called from azure, so we didn’t have to expose SAP.

**Comment by himanshush13** [comment]
Okay, Thank you @matt1as .  
For triggering repository, as mentioned, the command is- 
**- script: |
    npm start -- --host=<host> --protocol=http --username=<user> --password=Password --package=<Package>**
Here I am hard-coding the server credentials. Is there any other way to provide the Details for a secure hit to the server or we have to use only this command.

**Comment by matt1as** [comment]
You can also use env variables to pass the settings , to avoid having them in your script.

**Comment by himanshush13** [comment]
I am new to JS, plz ignore my silly questions 😜✌. Dotenv file might help here, I think.

**Comment by matt1as** [comment]
No worries.How you set env variables really depends on how you are running the script.

I’ll close this now, but please open a question if you have questions.
