### ISSUE TITLE
Package name is not substitute correctly

### ISSUE THREAD

**Issue by pacroy** [trr-official/abapunit2junit#7]
When executing with SAP_PACKAGE parameter, the package is not substituted in the request correctly as we can see in the response:

```
{
    "name": "StatusCodeError",
    "statusCode": 400,
    "message": "400 - \"<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?><exc:exception xmlns:exc=\\\"http://www.sap.com/abapxml/types/communicationframework\\\"><namespace id=\\\"com.sap.adt\\\"/><type id=\\\"ExceptionResourceBadRequest\\\"/><message lang=\\\"EN\\\">Request could not be understood by the server due to malformed syntax: Accept header missing</message><localizedMessage lang=\\\"EN\\\">Request could not be understood by the server due to malformed syntax: Accept header missing</localizedMessage><properties><entry key=\\\"com.sap.adt.communicationFramework.subType\\\">acceptHeaderMissing</entry></properties></exc:exception>\"",
    "error": "<?xml version=\"1.0\" encoding=\"utf-8\"?><exc:exception xmlns:exc=\"http://www.sap.com/abapxml/types/communicationframework\"><namespace id=\"com.sap.adt\"/><type id=\"ExceptionResourceBadRequest\"/><message lang=\"EN\">Request could not be understood by the server due to malformed syntax: Accept header missing</message><localizedMessage lang=\"EN\">Request could not be understood by the server due to malformed syntax: Accept header missing</localizedMessage><properties><entry key=\"com.sap.adt.communicationFramework.subType\">acceptHeaderMissing</entry></properties></exc:exception>",
    "options": {
        "jar": true,
        "method": "POST",
        "url": "https://vhcalnplci:44300/sap/bc/adt/abapunit/testruns",
        "auth": {
            "user": "DEVELOPER",
            "password": "*****",
            "pass": ""*****","
        },
        "headers": {
            "x-csrf-token": "TORF3f2b0Zym0ngBRxbHWw==",
            "Content-Type": "application/xml"
        },
        "body": "<?xml version='1.0' encoding='UTF-8'?>\n<aunit:runConfiguration xmlns:aunit='http://www.sap.com/adt/aunit'>\n    <external>\n        <coverage active='false'/>\n    </external>\n    <adtcore:objectSets xmlns:adtcore='http://www.sap.com/adt/core'>\n        <objectSet kind='inclusive'>\n            <adtcore:objectReferences>\n                <adtcore:objectReference adtcore:uri='/sap/bc/adt/vit/wb/object_type/devck/object_name/'/>\n            </adtcore:objectReferences>\n        </objectSet>\n    </adtcore:objectSets>\n</aunit:runConfiguration>",
        "insecure": true,
        "rejectUnauthorized": false,
        "simple": true,
        "resolveWithFullResponse": false,
        "transform2xxOnly": false
    },
    "response": {
        "statusCode": 400,
        "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><exc:exception xmlns:exc=\"http://www.sap.com/abapxml/types/communicationframework\"><namespace id=\"com.sap.adt\"/><type id=\"ExceptionResourceBadRequest\"/><message lang=\"EN\">Request could not be understood by the server due to malformed syntax: Accept header missing</message><localizedMessage lang=\"EN\">Request could not be understood by the server due to malformed syntax: Accept header missing</localizedMessage><properties><entry key=\"com.sap.adt.communicationFramework.subType\">acceptHeaderMissing</entry></properties></exc:exception>",
        "headers": {
            "content-type": "application/xml",
            "content-length": "574",
            "sap-cache-control": "+0 ",
            "sap-isc-uagent": "0",
            "sap-perf-fesrec": "178543.000000"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "vhcalnplci:44300",
                "port": "44300",
                "hostname": "vhcalnplci",
                "hash": null,
                "search": null,
                "query": null,
                "pathname": "/sap/bc/adt/abapunit/testruns",
                "path": "/sap/bc/adt/abapunit/testruns",
                "href": "https://vhcalnplci:44300/sap/bc/adt/abapunit/testruns"
            },
            "method": "POST",
            "headers": {
                "x-csrf-token": "TORF3f2b0Zym0ngBRxbHWw==",
                "Content-Type": "application/xml",
                "cookie": "sap-usercontext=sap-client=001; SAP_SESSIONID_NPL_001=avUG45ynhOus07uKmPI2wxh61c0LfxHpqd4IACcMznY%3d",
                "authorization": "Basic REVWRUxPUEVSOkRvd24xb2Fk",
                "content-length": 537
            }
        }
    }
}
```

**Comment by pacroy** [comment]
--> `adtcore:uri='/sap/bc/adt/vit/wb/object_type/devck/object_name/'`

**Comment by matt1as** [comment]
That's strange, when I run, both with system envs. or command line arguments it works. I've tested both with passing --package or setting the environment variable SAP_PACKAGE

Running
    npm.cmd start -- --host=saphost --protocol=https --username=user --password=password --insecure --package=ZTEST 

Results in
`<?xml version='1.0' encoding='UTF-8'?>
<aunit:runConfiguration xmlns:aunit='http://www.sap.com/adt/aunit'>
    <external>
        <coverage active='false'/>
    </external>
    <adtcore:objectSets xmlns:adtcore='http://www.sap.com/adt/core'>
        <objectSet kind='inclusive'>
            <adtcore:objectReferences>
                <adtcore:objectReference adtcore:uri='/sap/bc/adt/vit/wb/object_type/devck/object_name/ZTEST'/>
            </adtcore:objectReferences>
        </objectSet>
    </adtcore:objectSets>
</aunit:runConfiguration>`

and the result being generated. I just checked in another bug and some updates, please try again

**Comment by pacroy** [comment]
Looks like the problem happens with temporary packages i.e. package starts with `$` for both methods.

**Comment by matt1as** [comment]
I cannot reproduce it, if I put

                "env": {"SAP_PACKAGE":"$TMP"},

in my launch config (VSCode) I get the output

`<?xml version='1.0' encoding='UTF-8'?>
<aunit:runConfiguration xmlns:aunit='http://www.sap.com/adt/aunit'>
    <external>
        <coverage active='false'/>
    </external>
    <adtcore:objectSets xmlns:adtcore='http://www.sap.com/adt/core'>
        <objectSet kind='inclusive'>
            <adtcore:objectReferences>
                <adtcore:objectReference adtcore:uri='/sap/bc/adt/vit/wb/object_type/devck/object_name/$TMP'/>
            </adtcore:objectReferences>
        </objectSet>
    </adtcore:objectSets>
</aunit:runConfiguration>`

**Comment by pacroy** [comment]
Solved by escaping `$` character:

- Environment variable: `export SAP_PACKAGE=\$TMP`
- CLI Argument: `--package='\$TMP'`

But I got another error message `Request could not be understood by the server due to malformed syntax: Accept header missing`.

**Comment by matt1as** [comment]
I saw that in your earlier message and checked it, I can only find references to that together with Hana, and I'm on Netweaver, Could you run a unit test in Eclipse and capture the traffic, something must have changed in the call.

https://launchpad.support.sap.com/#/notes/0002563090

**Comment by pacroy** [comment]
Here it is, from 7.52

[abap_unit_752.txt](https://github.com/trr-official/abapunit2junit/files/2720702/abap_unit_752.txt)

**Comment by matt1as** [comment]
I've added the accept headers from your request 

Also I removed the possibility to use env variables, since it required to much code work to verify them

**Comment by pacroy** [comment]
Tested with [f861b26](https://github.com/trr-official/abapunit2junit/commit/f861b26f3d6f7619bc8a2ebfe09fe85c598f0c95) and got error:

```
TypeError: JSON.Stringify is not a function
    at /mnt/c/Users/pacroy/OneDrive/dev/abapunit2junit/index.js:94:40
```

After changing `JSON.Stringify(err)` to `JSON.stringify(err)`, it works fine with general packages.
But always got `<testsuites tests="0" failures="0"/>` for temporary packages.

Command I used: `npm start -- --host=vhcalnplci:44300 --protocol=https --username=DEVELOPER --password=***** --package=\$TEST --insecure`

**Comment by matt1as** [comment]
$ is a reserved character in URIs, and need to be %-encoded to work, you cannot escape it using \ in an URI

The following should work (works with %24ABAPGIT for me)

    npm start -- --host=vhcalnplci:44300 --protocol=https --username=DEVELOPER --password=***** --package=\%24TEST --insecure

**Comment by pacroy** [comment]
Works great now. Tested successfully on both 7.40 and 7.52. Good job! 👍

**Comment by matt1as** [comment]
Great, thank you for helping me finding bugs
